# 예외처리
## 예외란? ##
- 사용자의 잘못된 조작 또는 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류를 말한다. 
1. 일반 예외(Exception)
    - <b>컴파일러 체크 예외</b>라고도 하는데, 자바 소스를 컴파일하는 과정에서 예외처리 코드가 필요한지 검사하기 때문이다.   
    만약 예외 처리 코드가 없다면 컴파일 오류가 발생한다.
    - Exception을 상속받지만 Runtime Exception을 상속받지 않는 클래스
2. 실행 예외(Runtime Exception)
    - 컴파일하는 과정에서 예외 처리 코드를 검사하지 않는 예외를 말한다.
    - RuntimeException을 상속받은 클래스

## 예외 종류 ##
1. NullPointException
    - 가장 빈번하게 발생하는 실행 예외
    - <b>객체 참조가 없는 상태</b>, 즉 null 값을 갖는 참조 변수로 객체 접근 연산자 도트(.)를 사용했을때 발생
    ```java
    public class NullPointerExceptionExam{
        public static void main(String[] args){
            String data = null;
            System.out.println(data.toString()); // 예외발생
        }
    }
    ```

2. ArrayIndexOutOfBoundsException
    - 배열에서 인덱스 범위를 초과하여 사용할 경우 발생 
    ```java
    public class ArrayIndexOutOfBoundsExceptionExam{
        public static void main(String[] args){
            String data1 = args[0]; // 예외 발생
            String data2 = args[1];

            System.out.println("args[0] : " + data1);
            System.out.println("args[1] : " + data2);
        }
    }
    ```

3. NumberFormatException
    - 문자열로 되어 있는 데이터를 숫자로 변경하는 경우 자주 발생

    | 반환 타입 | 메소드명(매개변수) | 설명 |
    |:--------:| :---------------:| :----------:|
    |int | Integer.parseInt(String s) | 주어진 문자열을 정수로 변환해서 리턴 |
    |double | Double.parseDouble(String s) | 주어진 문자열을 실수로 변환해서 리턴 | 

    ```java
    public class NumberFormatExceptionExam{
        public static void main(String[] args){
            String data1 = "100";
            String data2 = "a100";

            int value1 = Integer.parseInt(data1);
            int value2 = Integer.parseInt(data2); // NumberFormatException 발생 

            int result = value1 + value2;
            System.out.println(data + "+" + data2 + "=" + result);

        }
    }
    ```

4. ClassCastException
    - 타입 변환(Casting)은 상위 클래스와 하위 클래스 간에 발생하고, 구현 클래스와 인터페이스 사이에도 발생한다.  
    이러한 관계가 아니면 클래스는 다른 클래스로 타입 변환이 불가능하다.  
    따라서 억지로 타입 변환을 시도하면 ClassCastException 예외가 발생한다.
    ```java
    public class ClassCastExceptionExam{
        public static void main(String[] args){
            Dog dog= new Dog();
            changeDog(dog);

            Cat cat = new Cat();
            changeDog(cat);
        }

        public static void changeDog(Animal animal){
            Dog dog = (Dog) animal; // ClassCastException 발생 가나ㅡㅇ
        }
    }

    class Animal{}
    class Dog extends Animal{}
    class Cat extends Animal{}
    ```
<br/>

## 예외 처리 코드 ##
- try-catch-finally 블록은 생성자 내부와 메소드 내부에서 작성되어 일반 예외와 실행 예외가 발생할 경우 예외 처리를 할 수 있도록 해준다.
- try 블록의 코드가 예외 발생 없이 정상 실행되면 catch 블록의 코드는 실행되지 않고 finally 블록의 코드를 실행  
만약 try 블록의 코드에서 예외가 발생하면 즉시 실행을 멈추고 catch 블록으로 이동하여 예외 처리 코드를 실행  
그리고 finally 블록의 코드를 실행한다. finally 블록은 옵션으로 생략 가능하다.  
try 블록과 catch 블록에서 return문을 사용하더라도 finally 블록은 항상 실행된다.
```java
public class TryCatchFinallyRuntimeException{
    public static void main(String[] args){
        try{
            Class clazz = Class.forName("java.lang.String2");
        }catch(ClassNotFoundexception e){
            System.out.println("클래스가 존재하지 않습니다.");
        }
    }
}
```
<br/>

## 다중 catch ##
- 예외별로 예외 처리를 다르게 할 경우 사용 
- catch 블록이 여러 개라 할지라도 단 하나의 catch 블록만 실행  
❓ why ❓   
    - try 블록에서 동시 다발적으로 예외가 발생하지 않고, 하나의 예외가 발생하면 즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문

    ```java
    public class CatchByExceptionKindExam{
        public static void main(String[] args){
            try{
                String data1 = args[0];
                String data2 = args[1];

                int value1 = Integer.parseInt(data1);
                int value2 = Integer.parseInt(data2);
                int result = value1 + value2;
                System.out.println(data1 + "+" + data2 + "=" + result);
            }catch(ArrayIndexOutOfBoundsException e){
                System.out.println("매개 값 부족 : " + e);
            }catch(NumberFormatException e){
                System.out.println("숫자 변환 불가 : " + e);
            }finally{
                System.out.println("다시 실행");
            }
        }
    }
    ```
<br/>

## catch 순서
- 다중 catch 블록을 작성 할때 주의할 점은 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다.
- 만약 상위 예외 클래스의 catch 블록이 위에 있다면, 하위 예외 클래스의 catch 블록은 실행되지 않는다.  
    ### ❓ why? ❓ ###
    - 하위 예외는 상위 예외를 상속했기 때문에 상위 예외 타입도 되기 때문

<br/>

## 자동 리소스 닫기
### 리소스란?
- 여러 가지 의미가 있겠지만 여기서는 데이터를 읽고 쓰는 객체라 생각하면 된다. 

### try-with-resources 사용 조건 ###
- 리소스 객체는 java.lang.AutoCloseable 인터페이를 구현하고 있어야 한다.
- AutoCloseable에는 close() 메소드가 정의되어 있는데 try-with-resources는 바로 이 close() 메소드를 자동 호출 

<br/>

## 예외 떠넘기기 ##
### throw 키워드
- 메소드 선언부 끝에 작성되어 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠넘기는 역할
```java
public void method1(){
    try{
        method2();
    }catch(ClassNotFoundException e){
        // 예외 처리 코드
        System.out.println("클래스가 존재하지 않습니다.");
    }
}

public void method2() throw ClassNotFoundException{
    Class clazz = Class.forName("java.lang.String2");
}
```
